import time
import pygame
import random
import sys
pygame.init()
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
(WIDTH, HEIGHT) = (800, 600)
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption('Тренажер для увеличения скорости печати')
font = pygame.font.Font(None, 36)
words_ru = [
    'яблоко',
    'банан',
    'вишня',
    'дыня',
    'ежевика',
    'фига',
    'виноград',
    'дыня',
    'киви',
    'лимон',
    'манго',
    'нектарин',
    'апельсин',
    'персик',
    'айва',
    'малина',
    'клубника',
    'мандарин',
    'угли',
    'ваниль',
    'арбуз',
    'абрикос',
    'голубика',
    'кокос',
    'питайя',
    'крыжовник',
    'черника',
    'имбирь',
    'ягодное варенье',
    'кивано',
    'лайм',
    'туцан',
    'кешью',
    'кунжут',
    'фисташки',
    'грецкий орех',
    'фундук',
    'черная смородина',
    'малина',
    'жимолость',
    'ежевика',
    'грейпфрут',
    'земляника',
    'инжир',
    'желтый груша',
    'каштан',
    'кубинская вишня',
    'листва клюквы',
    'виноград',
    'дыня',
    'голубика',
    'ежевичное варенье',
    'кокос',
    'лимон',
    'манго',
    'нектарин',
    'мента',
    'персик',
    'ревень',
    'сахар',
    'томат',
    'уцуца',
    'фенхель',
    'хурма',
    'чечевица',
    'шелковица',
    'эстрагон',
    'юкка',
    'мята',
    'щавель',
    'эвкалипт',
    'юфка',
    'финики',
    'ягоды боярышника',
    'лукум',
    'халва',
    'черноплодка',
    'цитрус',
    'шампанское',
    'эвкалипт',
    'ягода годжи',
    'шпинат',
    'ячмень',
    'овес',
    'рис',
    'пшеница',
    'картофель',
    'морковь',
    'свекла',
    'редиска',
    'брокколи',
    'капуста',
    'сельдерей',
    'перец',
    'баклажан',
    'чеснок',
    'лук',
    'петрушка',
    'тыква',
    'топинамбур',
    'морская капуста',
    'укроп',
    'горох',
    'перец чили',
    'ваниль',
    'тиранидер',
    'дюшес',
    'герань',
    'кизил',
    'кипарис',
    'ирис',
    'липа',
    'шалфей',
    'абрикос',
    'барбарис',
    'абсент',
    'василек',
    'гейхера',
    'киви',
    'лайм',
    'лилавка',
    'мальва',
    'нилка',
    'опунция',
    'паслен',
    'рамбутан',
    'смородина',
    'урек',
    'фасоль',
    'хурма',
    'цукаты',
    'черемша',
    'шпинат',
    'щавель',
    'эстрагон',
    'юстиция',
    'миндаль',
    'орех',
    'фундук',
    'астраханка',
    'бузина',
    'грумичата',
    'дуриан',
    'земляника',
    'калина',
    'лидерник',
    'макадамия',
    'нибонь',
    'овраг',
    'пекан',
    'рибарт',
    'смородина',
    'табибар',
    'узумба',
    'футорьян',
    'хайруйка',
    'циперус',
    'чианда',
    'шалфей',
    'эскулька',
    'юрополия',
    'айва',
    'бузульфа',
    'валериана',
    'герань',
    'жатва',
    'зокум',
    'иксодерма',
    'капорон',
    'ливана',
    'маргана',
    'никеря',
    'оматара',
    'писея',
    'рододендрон',
    'савана',
    'тампико',
    'униёль',
    'фасолевица',
    'хабаровка',
    'цавырпах',
    'чиропрокс',
    'шаталин',
    'эковица',
    'юшка',
    'ятрышка']
words_en = [
    'apple',
    'banana',
    'cherry',
    'date',
    'elderberry',
    'fig',
    'grape',
    'honeydew',
    'kiwi',
    'lemon',
    'mango',
    'nectarine',
    'orange',
    'peach',
    'quince',
    'raspberry',
    'strawberry',
    'tangerine',
    'ugli',
    'vanilla',
    'watermelon',
    'apricot',
    'blueberry',
    'coconut',
    'dragonfruit',
    'gooseberry',
    'huckleberry',
    'imbe',
    'jackfruit',
    'kiwano',
    'lime',
    'mulberry',
    'navel orange',
    'papaya',
    'quince',
    'rambutan',
    'starfruit',
    'ugly fruit',
    'vanilla bean',
    'white currant',
    'ximenia',
    'yellow watermelon',
    'zucchini',
    'almond',
    'cashew',
    'filbert',
    'pecan',
    'walnut',
    'blackberry',
    'boysenberry',
    'cranberry',
    'elderberry',
    'grapefruit',
    'honeyberry',
    'jujube',
    'lychee',
    'mandarin',
    'nectarine',
    'pear',
    'quince',
    'raisin',
    'strawberry',
    'tamarind',
    'ugli fruit',
    'vanilla',
    'watermelon',
    'apricot',
    'bell pepper',
    'carrot',
    'cucumber',
    'daikon',
    'eggplant',
    'fennel',
    'garlic',
    'horseradish',
    'iceberg lettuce',
    'jicama',
    'kale',
    'leek',
    'mushroom',
    'napa cabbage',
    'okra',
    'parsnip',
    'quince',
    'radish',
    'spinach',
    'turnip',
    'ugli fruit',
    'vanilla bean',
    'watercress',
    'yam',
    'zucchini',
    'artichoke',
    'beet',
    'celery',
    'dill',
    'endive',
    'fennel',
    'ginger',
    'honeydew melon',
    'iceberg lettuce',
    'jicama',
    'kale',
    'leek',
    'mushroom',
    'napa cabbage',
    'okra',
    'parsnip',
    'quince',
    'radicchio',
    'squash',
    'taro',
    'ugli fruit',
    'vinegar',
    'watercress',
    'yam',
    'zucchini',
    'asparagus',
    'broccoli',
    'cabbage',
    'dandelion greens',
    'endive',
    'fennel',
    'green bean',
    'herbes de provence',
    'iceberg lettuce',
    'jicama',
    'kohlrabi',
    'leek',
    'mushroom',
    'napa cabbage',
    'okra',
    'parsley',
    'quince',
    'rosemary',
    'sage',
    'thyme',
    'ugli fruit',
    'vanilla bean',
    'white radish',
    'xanthan gum',
    'yam',
    'zest',
    'artichoke',
    'basil',
    'cayenne pepper',
    'dill',
    'endive',
    'fennel',
    'ginger',
    'honey',
    'iceberg lettuce',
    'jicama',
    'kale',
    'lavender',
    'mint',
    'napa cabbage',
    'okra',
    'parsnips',
    'quince',
    'radishes',
    'sorrel',
    'tarragon',
    'ugli fruit',
    'vanilla',
    'watercress',
    'yam',
    'zest']
current_language = None
current_word = None
input_word = ''
correct_words = 0

def draw_text(text, color, x, y):
    text_surface = font.render(text, True, color)
    screen.blit(text_surface, (x, y))

while True:
    screen.fill(WHITE)
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
        if event.type == pygame.KEYDOWN:
            Time = 60
            if current_language is None:
                if event.key == pygame.K_r:
                    current_language = 'ru'
                    start_time = time.time()
                elif event.key == pygame.K_e:
                    current_language = 'en'
                    start_time = time.time()

        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_RETURN:
                if input_word == current_word:
                    correct_words += 1
                    current_word = None
                    input_word = ''
            elif event.key == pygame.K_BACKSPACE:
                input_word = input_word[:-1]
            else:
                input_word += event.unicode

    if current_language is None:
        draw_text('Выберите язык:', BLACK, WIDTH // 2 - 100, HEIGHT // 2 - 50)
        draw_text("Нажмите 'R' для русского, 'E' для английского", BLACK, WIDTH // 2 - 290, HEIGHT // 2)
    else:
        if current_word is None:
            if current_language == 'ru':
                current_word = random.choice(words_ru)
            else:
                current_word = random.choice(words_en)

        if time.time() - start_time > Time:
            draw_text('Истёк лимит времени!', RED, 20, 450)
            draw_text(f'Количество верно введенных слов: {correct_words}', RED, 20, 500)
            pygame.display.flip()
            time.sleep(3)
            start_time = time.time()
            current_language = None
            correct_words = 0
            Time = 60
        else:
            draw_text('Текущее слово:', BLACK, 20, 50)
            draw_text(current_word, BLACK, 20, 100)
            draw_text('Введите слово:', BLACK, 20, 200)
            draw_text(input_word, BLACK, 20, 250)
            draw_text('Осталось времени: {:.1f} сек'.format(Time - (time.time() - start_time)), RED, 20, 350)
            draw_text('Количество верно введенных слов: {}'.format(correct_words), BLACK, 20, 400)

        pygame.display.flip()
